name: Lint and check

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
       - name: Shell Linter
         uses: azohra/shell-linter@v0.1.0
       - name: shellcheck
         uses: ludeeus/action-shellcheck@0.1.0
